"""WITNESS — proving the boundary actually ran.

Every module here produces a guarantee, and every one of those guarantees
rests on the same unexamined assumption: that the enforcement code ran at
all, on every call, and that its record is complete.

That assumption is exactly what an operator cannot check. The reports are
generated by the same process they describe. `covenant.blocked` counts
appear because the Covenant appended them; if a call had slipped past the
gate entirely, nothing would appear, and an empty violation list looks
identical to a perfect record. Absence of evidence renders as evidence of
absence, which is the one reading it must never have.

    "no violations were recorded" and
    "no violations occurred" and
    "the check never ran"

are three different states that all print as silence.

So enforcement decisions are witnessed into their own hash chain, separate
from the fact that the kernel already seals events. Each decision carries
the digest of the one before it, so the chain has two properties the
per-event seals do not:

  * COMPLETE. Every gated call appends a decision — allowed as well as
    refused. A call with no decision is a gap, and verify() finds gaps by
    comparing the witnessed calls against the tool calls in the log.
    Silence is no longer indistinguishable from compliance.
  * TAMPER-EVIDENT. Removing or editing a decision breaks every link after
    it. You cannot delete the one refusal that embarrasses you without
    invalidating the rest of the chain, and verify() names the exact index
    where the break begins.

This is what turns "the agent followed the specification" from a claim into
something with evidence behind it. The chain can be exported and checked by
someone who does not trust this process and does not have to: verification
needs only the decisions and a hash function.

WHAT IT DOES NOT PROVE. The chain is only as trustworthy as the storage it
lives in — a process that can rewrite the whole log can rewrite the whole
chain, recomputing every link. What it defeats is SELECTIVE edits, which is
the realistic failure: a dropped record, a quietly flipped verdict, a
deleted refusal. Anchoring the head digest somewhere this process cannot
reach (a commit message, an external log) closes the rest, and head() is
what you would anchor.
"""

from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass, field

from .kernel import EventLog

ALLOWED = "allowed"
REFUSED = "refused"
GENESIS = "0" * 64


def _digest(payload: str) -> str:
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class Decision:
    """One witnessed enforcement decision."""
    index: int
    prev: str
    tool: str
    verdict: str
    clauses: tuple[str, ...] = ()
    ts: float = 0.0
    digest: str = ""

    def payload(self) -> str:
        """The bytes this link commits to. Canonical and sorted, so the
        same decision always hashes identically."""
        return json.dumps({"index": self.index, "prev": self.prev,
                           "tool": self.tool, "verdict": self.verdict,
                           "clauses": list(self.clauses),
                           "ts": round(self.ts, 6)},
                          sort_keys=True, separators=(",", ":"))

    def recompute(self) -> str:
        return _digest(self.payload())

    def to_dict(self) -> dict:
        return {"index": self.index, "prev": self.prev, "tool": self.tool,
                "verdict": self.verdict, "clauses": list(self.clauses),
                "ts": self.ts, "digest": self.digest}

    @classmethod
    def from_dict(cls, d: dict) -> "Decision":
        return cls(index=int(d.get("index", 0)),
                   prev=str(d.get("prev", GENESIS)),
                   tool=str(d.get("tool", "")),
                   verdict=str(d.get("verdict", "")),
                   clauses=tuple(d.get("clauses") or ()),
                   ts=float(d.get("ts", 0.0)),
                   digest=str(d.get("digest", "")))


@dataclass
class Audit:
    """The result of checking a chain."""
    length: int = 0
    intact: bool = True
    broken_at: int | None = None
    gaps: list[str] = field(default_factory=list)
    allowed: int = 0
    refused: int = 0
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.intact and not self.gaps and not self.problems

    def describe(self) -> str:
        if not self.length:
            return ("witness: no decisions recorded — the boundary has not "
                    "run, or nothing has been gated yet")
        head = (f"witness: {self.length} decision(s) · {self.refused} "
                f"refused / {self.allowed} allowed")
        if self.ok:
            return head + "\n  chain intact, every gated call accounted for"
        lines = [head]
        if not self.intact:
            lines.append(f"  !! chain broken at index {self.broken_at} — "
                         f"a decision was edited or removed")
        for g in self.gaps:
            lines.append(f"  !! no decision witnessed for: {g}")
        for p in self.problems:
            lines.append(f"  !! {p}")
        return "\n".join(lines)


class Witness:
    """The enforcement chain: append-only, self-verifying."""

    def __init__(self, log: EventLog) -> None:
        self.log = log
        self.chain: list[Decision] = []

    # -- appending ----------------------------------------------------------

    def head(self) -> str:
        """The digest to anchor externally. Everything the chain has seen
        is committed to by this one value."""
        return self.chain[-1].digest if self.chain else GENESIS

    def record(self, tool: str, verdict: str,
               clauses: tuple[str, ...] | list[str] = ()) -> Decision:
        """Witness one decision — including an allowance.

        Recording allowances is the point. A chain of refusals proves only
        that some refusals happened; a chain of every decision proves that
        no call went unjudged, which is the stronger and more useful claim.
        """
        d = Decision(index=len(self.chain), prev=self.head(), tool=tool,
                     verdict=verdict, clauses=tuple(clauses),
                     ts=time.time())
        d = Decision(**{**d.__dict__, "digest": d.recompute()})
        self.chain.append(d)
        self.log.append("witness.decision", d.to_dict(), actor="kernel")
        return d

    def allow(self, tool: str) -> Decision:
        return self.record(tool, ALLOWED)

    def refuse(self, tool: str, clauses) -> Decision:
        return self.record(tool, REFUSED, tuple(clauses))

    # -- verification -------------------------------------------------------

    def verify(self, expect_tools: list[str] | None = None) -> Audit:
        """Check the chain end to end.

        `expect_tools` is the list of calls that SHOULD have been judged —
        normally the tool.call events in the log. Comparing it against the
        chain is what turns silence into a finding.
        """
        a = Audit(length=len(self.chain))
        prev = GENESIS
        for i, d in enumerate(self.chain):
            if d.index != i or d.prev != prev:
                a.intact = False
                a.broken_at = i
                break
            if d.digest != d.recompute():
                a.intact = False
                a.broken_at = i
                a.problems.append(f"decision {i} does not match its digest")
                break
            prev = d.digest
            if d.verdict == REFUSED:
                a.refused += 1
            elif d.verdict == ALLOWED:
                a.allowed += 1
            else:
                a.problems.append(f"decision {i} has an unknown verdict "
                                  f"{d.verdict!r}")

        if expect_tools is not None and a.intact:
            witnessed: dict[str, int] = {}
            for d in self.chain:
                witnessed[d.tool] = witnessed.get(d.tool, 0) + 1
            for tool in expect_tools:
                if witnessed.get(tool, 0) > 0:
                    witnessed[tool] -= 1
                else:
                    a.gaps.append(tool)
        return a

    # -- portability --------------------------------------------------------

    def export(self) -> list[dict]:
        """The chain, for checking somewhere this process cannot reach."""
        return [d.to_dict() for d in self.chain]

    @staticmethod
    def check(exported: list[dict]) -> Audit:
        """Verify an exported chain with no access to this process.

        A static method on purpose: verification must not need the object
        that produced the chain, or it would be the same process vouching
        for itself again.
        """
        a = Audit(length=len(exported))
        prev = GENESIS
        for i, raw in enumerate(exported):
            d = Decision.from_dict(raw)
            if d.index != i or d.prev != prev or d.digest != d.recompute():
                a.intact = False
                a.broken_at = i
                break
            prev = d.digest
            if d.verdict == REFUSED:
                a.refused += 1
            else:
                a.allowed += 1
        return a

    def rebuild(self) -> int:
        """Reload the chain from the sealed log (after a restart)."""
        self.chain = [Decision.from_dict(ev.data)
                      for ev in self.log.events()
                      if ev.type == "witness.decision"]
        return len(self.chain)

    def report(self, expect_tools: list[str] | None = None) -> str:
        return self.verify(expect_tools).describe() + \
            f"\n  head: {self.head()[:16]}"


if __name__ == "__main__":
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as td:
        log = EventLog(Path(td) / "log.jsonl")
        w = Witness(log)

        # -- an empty chain says so, rather than looking clean -------------
        assert "has not run" in w.verify().describe()
        assert w.head() == GENESIS

        # -- decisions chain together ---------------------------------------
        w.allow("read_file")
        w.refuse("write_file", ["1"])
        w.allow("run_command")
        w.refuse("delete_path", ["3", "5"])
        a = w.verify()
        assert a.ok and a.length == 4
        assert a.allowed == 2 and a.refused == 2
        assert "chain intact" in a.describe()

        # each link commits to the one before it
        assert w.chain[0].prev == GENESIS
        for i in range(1, len(w.chain)):
            assert w.chain[i].prev == w.chain[i - 1].digest

        # the head changes with every decision
        before = w.head()
        w.allow("read_file")
        assert w.head() != before

        # -- COMPLETENESS: a call nobody judged is a gap -------------------
        gated = ["read_file", "write_file", "run_command", "delete_path",
                 "read_file", "apply_patch"]     # apply_patch never witnessed
        a = w.verify(gated)
        assert not a.ok and a.gaps == ["apply_patch"], a.describe()
        assert "no decision witnessed for: apply_patch" in a.describe()
        # with the full set accounted for, it is clean again
        assert w.verify(gated[:-1]).ok

        # -- TAMPER-EVIDENCE: a flipped verdict breaks the chain -----------
        exported = w.export()
        assert Witness.check(exported).ok
        tampered = [dict(d) for d in exported]
        tampered[1]["verdict"] = ALLOWED          # hide the refusal
        broken = Witness.check(tampered)
        assert not broken.intact and broken.broken_at == 1, broken.describe()

        # -- a deleted decision breaks it too ------------------------------
        dropped = [dict(d) for d in exported]
        del dropped[2]
        for i, d in enumerate(dropped):
            d["index"] = i                        # even after renumbering
        assert not Witness.check(dropped).intact

        # -- appended-but-unlinked records are caught ----------------------
        forged = [dict(d) for d in exported]
        forged.append({"index": len(forged), "prev": GENESIS,
                       "tool": "write_file", "verdict": ALLOWED,
                       "clauses": [], "ts": 0.0, "digest": "0" * 64})
        assert not Witness.check(forged).intact

        # -- verification needs nothing from this process ------------------
        # (Witness.check is static; the exported list is plain JSON)
        assert Witness.check(json.loads(json.dumps(exported))).ok

        # -- the chain survives a restart ----------------------------------
        reopened = Witness(EventLog(Path(td) / "log.jsonl"))
        assert reopened.rebuild() == len(w.chain)
        assert reopened.verify().ok
        assert reopened.head() == w.head(), "head did not survive reload"

        # -- an unknown verdict is a problem, not a silent pass ------------
        odd = Witness(EventLog(Path(td) / "odd.jsonl"))
        odd.record("write_file", "maybe")
        assert not odd.verify().ok

        # -- the report carries the anchorable head ------------------------
        assert "head: " in w.report()

    print("WITNESS SELF-TEST PASS")
